version: '3'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.config:/etc/nginx/conf.d/default.conf
    ports:
      - "7878:80"
    depends_on:
      - oxigraph
  oxigraph:
    image: ghcr.io/oxigraph/oxigraph:latest
    platform: linux/amd64
    volumes:
      - ./data:/data